language: go
go:
  - 1.x
  - 1.11.x
os:
  - linux
sudo: required
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
  - go get -d ./...
  - sudo modprobe vmw_vsock_vmci_transport
  - sudo chmod 666 /dev/vsock
script:
  - go build -tags=gofuzz ./...
  - go vet ./...
  - staticcheck ./...
  - golint -set_exit_status ./...
  - go test -v -race ./...
